-- MySQL Script generated by MySQL Workbench
-- Sun Mar 19 21:41:35 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `idCourses` INT NOT NULL,
  PRIMARY KEY (`idCourses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teaches` (
  `idteaches` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  PRIMARY KEY (`idteaches`, `Courses_idCourses`),
  INDEX `fk_teaches_Courses2_idx` (`Courses_idCourses` ASC),
  CONSTRAINT `fk_teaches_Courses2`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Group`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Group` (
  `Group_id` INT NOT NULL,
  `teaches_idteaches` INT NOT NULL,
  PRIMARY KEY (`Group_id`),
  INDEX `fk_Group_teaches1_idx` (`teaches_idteaches` ASC),
  CONSTRAINT `fk_Group_teaches1`
    FOREIGN KEY (`teaches_idteaches`)
    REFERENCES `mydb`.`teaches` (`idteaches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Consist of`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Consist of` (
  `idConsist of` INT NOT NULL,
  `Group_Group_id` INT NOT NULL,
  PRIMARY KEY (`idConsist of`),
  INDEX `fk_Consist of_Group1_idx` (`Group_Group_id` ASC),
  CONSTRAINT `fk_Consist of_Group1`
    FOREIGN KEY (`Group_Group_id`)
    REFERENCES `mydb`.`Group` (`Group_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professor` (
  `Professor_id` INT NOT NULL,
  `Consist of_idConsist of` INT NOT NULL,
  `teaches_idteaches` INT NOT NULL,
  PRIMARY KEY (`Professor_id`, `teaches_idteaches`),
  INDEX `fk_Professor_Consist of1_idx` (`Consist of_idConsist of` ASC),
  INDEX `fk_Professor_teaches1_idx` (`teaches_idteaches` ASC),
  CONSTRAINT `fk_Professor_Consist of1`
    FOREIGN KEY (`Consist of_idConsist of`)
    REFERENCES `mydb`.`Consist of` (`idConsist of`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professor_teaches1`
    FOREIGN KEY (`teaches_idteaches`)
    REFERENCES `mydb`.`teaches` (`idteaches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Semester` (
  `idSemester` INT NOT NULL,
  `teaches_idteaches` INT NOT NULL,
  PRIMARY KEY (`idSemester`),
  INDEX `fk_Semester_teaches1_idx` (`teaches_idteaches` ASC),
  CONSTRAINT `fk_Semester_teaches1`
    FOREIGN KEY (`teaches_idteaches`)
    REFERENCES `mydb`.`teaches` (`idteaches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Courses`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Courses` (
  `idCourses` INT NOT NULL,
  PRIMARY KEY (`idCourses`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`teaches`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`teaches` (
  `idteaches` INT NOT NULL,
  `Courses_idCourses` INT NOT NULL,
  PRIMARY KEY (`idteaches`, `Courses_idCourses`),
  INDEX `fk_teaches_Courses2_idx` (`Courses_idCourses` ASC),
  CONSTRAINT `fk_teaches_Courses2`
    FOREIGN KEY (`Courses_idCourses`)
    REFERENCES `mydb`.`Courses` (`idCourses`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Managed by`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Managed by` (
  `idManaged by` INT NOT NULL,
  PRIMARY KEY (`idManaged by`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Worked in`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Worked in` (
  `idWorked in` INT NOT NULL,
  PRIMARY KEY (`idWorked in`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Supervice`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Supervice` (
  `idSupervice` INT NOT NULL,
  PRIMARY KEY (`idSupervice`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`runs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`runs` (
  `idruns` INT NOT NULL,
  PRIMARY KEY (`idruns`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Professors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Professors` (
  `Professors_id` INT NOT NULL,
  `teaches_idteaches1` INT NOT NULL,
  `Professors_name` VARCHAR(45) NOT NULL,
  `Professors_age` INT NULL,
  `Professors_rank` INT NULL,
  `research_speciality` INT NULL,
  `Managed by_idManaged by` INT NOT NULL,
  `Worked in_idWorked in` INT NOT NULL,
  `Supervice_idSupervice` INT NOT NULL,
  `runs_idruns` INT NOT NULL,
  PRIMARY KEY (`Professors_id`),
  INDEX `fk_Professors_teaches2_idx` (`teaches_idteaches1` ASC),
  INDEX `fk_Professors_Managed by1_idx` (`Managed by_idManaged by` ASC),
  INDEX `fk_Professors_Worked in1_idx` (`Worked in_idWorked in` ASC),
  INDEX `fk_Professors_Supervice1_idx` (`Supervice_idSupervice` ASC),
  INDEX `fk_Professors_runs1_idx` (`runs_idruns` ASC),
  CONSTRAINT `fk_Professors_teaches2`
    FOREIGN KEY (`teaches_idteaches1`)
    REFERENCES `mydb`.`teaches` (`idteaches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_Managed by1`
    FOREIGN KEY (`Managed by_idManaged by`)
    REFERENCES `mydb`.`Managed by` (`idManaged by`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_Worked in1`
    FOREIGN KEY (`Worked in_idWorked in`)
    REFERENCES `mydb`.`Worked in` (`idWorked in`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_Supervice1`
    FOREIGN KEY (`Supervice_idSupervice`)
    REFERENCES `mydb`.`Supervice` (`idSupervice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Professors_runs1`
    FOREIGN KEY (`runs_idruns`)
    REFERENCES `mydb`.`runs` (`idruns`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Semester`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Semester` (
  `idSemester` INT NOT NULL,
  `teaches_idteaches` INT NOT NULL,
  PRIMARY KEY (`idSemester`),
  INDEX `fk_Semester_teaches1_idx` (`teaches_idteaches` ASC),
  CONSTRAINT `fk_Semester_teaches1`
    FOREIGN KEY (`teaches_idteaches`)
    REFERENCES `mydb`.`teaches` (`idteaches`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Work on`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Work on` (
  `idWork on` INT NOT NULL,
  `Supervice_idSupervice` INT NOT NULL,
  PRIMARY KEY (`idWork on`, `Supervice_idSupervice`),
  INDEX `fk_Work on_Supervice1_idx` (`Supervice_idSupervice` ASC),
  CONSTRAINT `fk_Work on_Supervice1`
    FOREIGN KEY (`Supervice_idSupervice`)
    REFERENCES `mydb`.`Supervice` (`idSupervice`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Project`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Project` (
  `Project_number` INT NOT NULL,
  `NSF` VARCHAR(45) NOT NULL,
  `Starting_date` DATETIME NOT NULL,
  `Ending_date` DATETIME NOT NULL,
  `Budzet` INT NOT NULL,
  `Managed by_idManaged by` INT NOT NULL,
  `Worked in_idWorked in` INT NOT NULL,
  `Work on_idWork on` INT NOT NULL,
  INDEX `fk_Project_Managed by1_idx` (`Managed by_idManaged by` ASC),
  INDEX `fk_Project_Worked in1_idx` (`Worked in_idWorked in` ASC),
  INDEX `fk_Project_Work on1_idx` (`Work on_idWork on` ASC),
  CONSTRAINT `fk_Project_Managed by1`
    FOREIGN KEY (`Managed by_idManaged by`)
    REFERENCES `mydb`.`Managed by` (`idManaged by`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Worked in1`
    FOREIGN KEY (`Worked in_idWorked in`)
    REFERENCES `mydb`.`Worked in` (`idWorked in`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Project_Work on1`
    FOREIGN KEY (`Work on_idWork on`)
    REFERENCES `mydb`.`Work on` (`idWork on`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Major`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Major` (
  `idMajor` INT NOT NULL,
  PRIMARY KEY (`idMajor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Advisor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Advisor` (
  `idAdvisor` INT NOT NULL,
  PRIMARY KEY (`idAdvisor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Graduate_Student`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Graduate_Student` (
  `Student_id` INT NOT NULL,
  `Work on_idWork on` INT NOT NULL,
  `Major_idMajor` INT NOT NULL,
  `Advisor_idAdvisor` INT NOT NULL,
  `Advisor_idAdvisor1` INT NOT NULL,
  PRIMARY KEY (`Student_id`, `Major_idMajor`, `Advisor_idAdvisor1`),
  INDEX `fk_Graduate_Student_Work on1_idx` (`Work on_idWork on` ASC),
  INDEX `fk_Graduate_Student_Major1_idx` (`Major_idMajor` ASC),
  INDEX `fk_Graduate_Student_Advisor1_idx` (`Advisor_idAdvisor` ASC),
  INDEX `fk_Graduate_Student_Advisor2_idx` (`Advisor_idAdvisor1` ASC),
  CONSTRAINT `fk_Graduate_Student_Work on1`
    FOREIGN KEY (`Work on_idWork on`)
    REFERENCES `mydb`.`Work on` (`idWork on`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Graduate_Student_Major1`
    FOREIGN KEY (`Major_idMajor`)
    REFERENCES `mydb`.`Major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Graduate_Student_Advisor1`
    FOREIGN KEY (`Advisor_idAdvisor`)
    REFERENCES `mydb`.`Advisor` (`idAdvisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Graduate_Student_Advisor2`
    FOREIGN KEY (`Advisor_idAdvisor1`)
    REFERENCES `mydb`.`Advisor` (`idAdvisor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Department`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Department` (
  `Department_num` INT NOT NULL,
  `Department_address` VARCHAR(45) NOT NULL,
  `Major_idMajor` INT NOT NULL,
  PRIMARY KEY (`Department_num`),
  INDEX `fk_Department_Major1_idx` (`Major_idMajor` ASC),
  CONSTRAINT `fk_Department_runs1`
    FOREIGN KEY (`Department_num`)
    REFERENCES `mydb`.`runs` (`idruns`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Department_Major1`
    FOREIGN KEY (`Major_idMajor`)
    REFERENCES `mydb`.`Major` (`idMajor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
