-- MySQL Script generated by MySQL Workbench
-- Wed Mar 22 22:02:28 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Boats`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Boats` (
  `bid` INT NOT NULL,
  `bname` VARCHAR(45) NOT NULL,
  `color` VARCHAR(45) NOT NULL,
  `Boatscol` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`bid`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reserve`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Reserve` (
  `sid` INT NOT NULL,
  `bid` VARCHAR(45) NULL,
  `day` VARCHAR(45) NULL,
  `bid` INT NOT NULL,
  PRIMARY KEY (`sid`),
  INDEX `fk_Reserve_Boats1_idx` (`bid` ASC),
  CONSTRAINT `fk_Reserve_Boats1`
    FOREIGN KEY (`bid`)
    REFERENCES `mydb`.`Boats` (`bid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sailors`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sailors` (
  `sid` INT NOT NULL,
  `sname` VARCHAR(45) NOT NULL,
  `rating` INT NOT NULL,
  `age` INT NOT NULL,
  `sid` INT NOT NULL,
  PRIMARY KEY (`sid`),
  INDEX `fk_Sailors_Reserve1_idx` (`sid` ASC),
  CONSTRAINT `fk_Sailors_Reserve1`
    FOREIGN KEY (`sid`)
    REFERENCES `mydb`.`Reserve` (`sid`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
